dist: bionic
sudo: required
language: python
python:
  - 3.8
# Cache Dependencies
cache: pip
addons:
  apt:
    packages:
    - optipng  # for optimize images plugin
    - libjpeg-progs  # for jpegtran for optimize images plugin
    - tree  # for file listings

before_install:
# command to install dependencies
install:
  - pip install --upgrade pip
  - pip install -r requirements.txt
before_script:
  - invoke --list
script:
  - invoke build --carefully --travis
# see https://github.com/timwis/vizwit/blob/master/.travis.yml#L15-L21
# see https://travis-ci.org/MinchinWeb/blog.minchin.ca
deploy:
  provider: pages
  local_dir: output
  target-branch: master
  skip-cleanup: true
  keep-history: true
  github_token: $GITHUB_TOKEN  # Set in travis-ci.org dashboard
  fqdm: minchin.ca
  on:
    branch: pelican
after_script:
   - tree -aC output
